import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-app.js';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-auth.js';
import {getFirestore,doc,getDoc,collection,query,where,limit,getDocs,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.3.0/firebase-firestore.js';
const app=initializeApp({apiKey:'AIzaSyD1DVagJs2Tzfhou-7Yiz3dM-Zz_FAA7HY',authDomain:'gilapips.firebaseapp.com',projectId:'gilapips',storageBucket:'gilapips.firebasestorage.app',messagingSenderId:'1008903422324',appId:'1:1008903422324:web:6174b01279ccb415afac21'});
const auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);let generation=0,busy=false;
const message=t=>$('notice').textContent=t;
async function run(fn){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){message(e.code==='auth/popup-closed-by-user'?'Login dibatalkan.':e.code==='auth/unauthorized-domain'?'Domain ini belum dibenarkan dalam Firebase Authentication.':e.code==='auth/popup-blocked'?'Benarkan popup Google dalam browser dan cuba lagi.':e.code==='permission-denied'?'Akses tidak dibenarkan. Semak role admin.':'Tindakan belum berjaya. Semak internet dan cuba semula.');}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function checkAccess(user,version){$('dashboard').hidden=true;$('requests').replaceChildren();$('refresh').hidden=false;$('access').textContent='Menyemak akses…';const s=await getDoc(doc(db,'admins',user.uid));if(version!==generation)return;if(!s.exists()||s.data().enabled!==true){$('access').textContent='Akaun ini belum diberikan akses pentadbir. Minta pemilik projek aktifkan role admin.';message('Login berjaya. Akses admin belum aktif.');return;}$('access').textContent='Akses pentadbir aktif.';$('dashboard').hidden=false;message('Selamat kembali.');await loadRequests(version);}
async function loadRequests(version=generation){const panel=$('requests');panel.textContent='Memuatkan permohonan…';const s=await getDocs(query(collection(db,'verificationRequests'),where('status','==','pending'),limit(50)));if(version!==generation)return;panel.replaceChildren();$('count').textContent=s.size===50?'50 permohonan dipaparkan. Muat semula selepas semakan untuk melihat permohonan berikutnya.':`${s.size} permohonan menunggu semakan.`;if(s.empty){panel.textContent='Semua selesai. Tiada permohonan menunggu semakan.';return;}for(const item of s.docs){const data=item.data(),row=document.createElement('article');row.className='row';const details=document.createElement('div'),name=document.createElement('strong'),type=document.createElement('p'),uid=document.createElement('p');name.textContent=data.registrationName;type.textContent=(data.type==='trading'?'Trading':'Public Gold')+' · '+(data.submittedAt?.toDate?new Intl.DateTimeFormat('ms-MY',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kuala_Lumpur'}).format(data.submittedAt.toDate()):'Tarikh belum tersedia');uid.className='uid';uid.textContent='UID: '+item.id;details.append(name,type,uid);const actions=document.createElement('div');actions.className='actions';for(const [label,status] of [['Luluskan','approved'],['Tolak','rejected']]){const b=document.createElement('button');b.textContent=label;if(status==='rejected')b.className='danger';b.onclick=()=>{if(!confirm(status==='approved'?'Rekod pendaftaran ini sudah disahkan bawah GilaPips?':'Tolak permohonan ini? Ahli boleh menghantar semula.'))return;run(async()=>{const user=auth.currentUser;if(!user||version!==generation)return;await updateDoc(doc(db,'verificationRequests',item.id),{status,reviewedAt:serverTimestamp(),reviewedBy:user.uid});message(status==='approved'?'Permohonan diluluskan.':'Permohonan ditolak.');await loadRequests(version);});};actions.append(b);}row.append(details,actions);panel.append(row);}}
$('signin').disabled=false;$('signin').onclick=()=>run(()=>signInWithPopup(auth,new GoogleAuthProvider()));$('logout').onclick=()=>run(()=>signOut(auth));$('reload').onclick=()=>run(()=>loadRequests());$('refresh').onclick=()=>run(()=>auth.currentUser&&checkAccess(auth.currentUser,generation));
onAuthStateChanged(auth,user=>{const version=++generation;$('login').hidden=!!user;$('account').hidden=!user;$('dashboard').hidden=true;$('requests').replaceChildren();$('count').textContent='';if(!user){message('Login untuk membuka ruang pengurusan.');$('identity').textContent='';$('uid').textContent='';return;}$('identity').textContent=user.email||user.displayName||'Pentadbir';$('uid').textContent='UID akaun: '+user.uid;checkAccess(user,version).catch(()=>{if(version===generation){$('access').textContent='Akses belum dapat disemak.';message('Semak sambungan dan cuba Semak semula.');}});});
